### ISSUE TITLE
dlib-dnn-pimpl-wrapper\NetPimpl.cpp(310): fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by msnhs** [reunanen/annonet#5]
First of all, I really appreciate the project.

When compiling annonet_train_cuda & annonet_train_cpu version both
Error in NetPimpl.cpp(310): fatal error C1060
Compiler is out of heap space in visual studio 2015 x64 compiler
An error occurs when importing the source code dlib library into the precompiled file ex: dlib19.16.99_release_64bit_msvc1900.lib

I would appreciate your help.

**Comment by reunanen** [comment]
@msnhs : yeah, the MSVC 2015 IDE will do that.

Can you please try to build from Command Prompt instead:

`"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" annonet_cuda.sln /p:Configuration=Release /p:Platform=x64`

**Comment by msnhs** [comment]
Thanks for your advice.
I already solved this problem.
